BRCM_SAI_VERSION = 3.3.2.4-5

export BRCM_SAI_VERSION

BRCM_SAI = libsaibcm_$(BRCM_SAI_VERSION)_amd64.deb
$(BRCM_SAI)_PATH = files/broadcom-binary

BRCM_SAI_DEV = libsaibcm-dev_$(BRCM_SAI_VERSION)_amd64.deb
$(BRCM_SAI_DEV)_PATH = files/broadcom-binary

SONIC_COPY_DEBS += $(BRCM_SAI) $(BRCM_SAI_DEV)
$(BRCM_SAI_DEV)_DEPENDS += $(BRCM_SAI)

BRCM_OPENNSL_KERNEL = libsaibcm-modules-3.16.0-5-amd64_$(BRCM_SAI_VERSION)_amd64.deb
$(BRCM_OPENNSL_KERNEL)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(BRCM_OPENNSL_KERNEL)_PATH = files/broadcom-binary
SONIC_COPY_DEBS += $(BRCM_OPENNSL_KERNEL)
