OPENNSL_VERSION = 3.5.0.4

export OPENNSL_VERSION

BRCM_LIBOPENNSL = libopennsl_$(OPENNSL_VERSION)_amd64.deb
$(BRCM_LIBOPENNSL)_PATH = files/broadcom-binary
SONIC_COPY_DEBS += $(BRCM_LIBOPENNSL)

# Implicitly. BRCM_OPENNSL_KERNEL and BRCM_LIBOPENNSL_DEV is compiled with BRCM_LIBOPENNSL together
BRCM_OPENNSL_KERNEL = opennsl-modules-3.16.0-5-amd64_$(OPENNSL_VERSION)_amd64.deb
$(BRCM_OPENNSL_KERNEL)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(BRCM_OPENNSL_KERNEL)_PATH = files/broadcom-binary
SONIC_COPY_DEBS += $(BRCM_OPENNSL_KERNEL)

BRCM_LIBOPENNSL_DEV = libopennsl-dev_$(OPENNSL_VERSION)_amd64.deb
$(BRCM_LIBOPENNSL_DEV)_PATH = files/broadcom-binary
SONIC_COPY_DEBS += $(BRCM_LIBOPENNSL_DEV)
